server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.16.245:3306/access_control?characterEncoding=UTF-8
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sv.mjxt.web.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true